name: flexi
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.7
  provider: ^6.1.2
  equatable: ^2.0.5
  flutter_bloc: ^7.3.3
  hycop_light: ^0.4.26
  logging: ^1.0.2
  wifi_iot: ^0.3.19
  wifi_scan: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application
  assets:
    - assets/image/login_illustration.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Thin.ttf
          weight: 100
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900