name: flexi
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: '>=3.1.3 <4.0.0'





dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  http: ^1.1.0
  crypto: ^3.0.3
  flutter_advanced_switch: ^3.1.0
  network_info_plus: ^5.0.3
  permission_handler: ^11.3.1
  internet_connection_checker_plus: ^2.3.0
  wifi_iot: ^0.3.19
  freezed_annotation: ^2.4.1
  connectivity_plus: ^6.0.2
  socket_io_client: ^1.0.2
  socket_io:
    path: packages/socket_io
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.2.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2

flutter:

  uses-material-design: true

  # To add assets to your application
  assets:
    - assets/image/login_illustration.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Thin.ttf
          weight: 100
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900