name: flexi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  bluetooth_low_energy: ^6.0.2
  cloud_firestore: ^5.0.0
  connectivity_plus: ^6.0.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  flutter_advanced_switch: ^3.1.0
  flutter_blue_plus: ^1.32.6
  flutter_native_splash: ^2.4.0
  flutter_native_timezone_updated_gradle: ^2.0.3
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.1
  fluttertoast: ^8.2.5
  freezed_annotation: ^2.4.1
  google_mlkit_barcode_scanning: ^0.12.0
  google_sign_in: ^6.2.1
  go_router: ^13.2.0
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.19.0  
  json_annotation: ^4.8.1
  logging: ^1.2.0
  network_info_plus: ^5.0.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_manager: ^3.0.0
  qr_code_scanner: ^1.0.1
  riverpod: ^2.4.9
  sembast: ^3.7.1
  speech_to_text: ^6.6.0
  socket_io_client: ^1.0.2
  socket_io:
    path: packages/socket_io
  timezone: ^0.9.3
  translator: ^1.0.0
  url_launcher: ^6.2.6
  wifi_iot: ^0.3.19
  wifi_scan: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10


flutter:
  uses-material-design: true

  assets:
    - assets/image/login_illustration.png
    - assets/image/speak.png
    - assets/image/speaking.gif
    - assets/image/wifi_loading.gif
    - assets/image/google_logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Thin.ttf
          weight: 100
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900