name: flexi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  bluetooth_low_energy: ^6.0.2
  cloud_firestore: ^5.3.0
  connectivity_plus: ^6.0.5
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  flutter_advanced_switch: ^3.1.0
  flutter_blue_plus: ^1.32.12
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_timezone: ^3.0.1
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  google_sign_in: ^6.2.1
  go_router: ^14.2.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  network_info_plus: ^6.0.1
  mobile_scanner: ^5.2.3
  open_settings_plus: ^0.3.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  photo_manager: ^3.3.0
  qr_code_dart_scan: ^0.9.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  sembast: ^3.7.3+2
  speech_to_text: ^7.0.0
  socket_io_client: ^1.0.2
  timezone: ^0.9.4
  translator: ^1.0.0
  wifi_iot: ^0.3.19+1
  wifi_scan: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  assets:
    - assets/image/loading.gif
    - assets/image/login_illustration.png
    - assets/image/speak.png
    - assets/image/speaking.gif
    # - assets/image/google_logo.png
    - assets/template/escalator_guide.png
    - assets/template/restricted_area.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Thin.ttf
          weight: 100
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900